### ISSUE TITLE
Test set in the hallucination task

### ISSUE THREAD

**Issue by LetheSec** [Zhang-Yihao/Adversarial-Representation-Engineering#2]
Thanks for the nice work.

I would like to know where I can get the processed test set for the hallucination task ?

https://github.com/Zhang-Yihao/Adversarial-Representation-Engineering/blob/b8c51696630b29fc5eba7d216102601bdf8261b7/tqa_utils.py#L17

**Comment by Zhang-Yihao** [comment]
Hi,
thanks for pointing out this. The trustful qa dataset can be found in [Huggingface](https://huggingface.co/datasets/truthfulqa/truthful_qa). In fact, the data processing pipeline here is borrowed from [repe repo](https://github.com/andyzoujm/representation-engineering) as I mentioned in the README. 

Well there is one line that fixes the problem:
`dataset = load_dataset('truthful_qa', 'multiple_choice')['validation']`

I am using a local version simply due to I cannot access Huggingface directly in PRC, but the content is all the same.

If you have more questions about this, feel free to reply under this issue. Thanks a lot.

**Comment by LetheSec** [comment]
Thank you for your detailed reply.
